### ISSUE TITLE
Exception Schema already exists in PopulateTestEngine when reusing DB

### ISSUE THREAD

**Issue by tkilias** [exasol/script-languages-container-tool#200]
```
- PopulateTestEngine_bd2f349c75:
    Traceback (most recent call last):
      File "/home/vagrant/.cache/pypoetry/virtualenvs/exasol-script-languages-container-tool-fEttNriu-py3.8/lib/python3.8/site-packages/exasol_integration_test_docker_environment/lib/base/stoppable_base_task.py", line 27, in run
        yield from task_generator
      File "/home/vagrant/.cache/pypoetry/virtualenvs/exasol-script-languages-container-tool-fEttNriu-py3.8/lib/python3.8/site-packages/exasol_integration_test_docker_environment/lib/base/timeable_base_task.py", line 120, in run
        yield from task_generator
      File "/home/vagrant/.cache/pypoetry/virtualenvs/exasol-script-languages-container-tool-fEttNriu-py3.8/lib/python3.8/site-packages/exasol_integration_test_docker_environment/lib/base/base_task.py", line 248, in run
        raise e
      File "/home/vagrant/.cache/pypoetry/virtualenvs/exasol-script-languages-container-tool-fEttNriu-py3.8/lib/python3.8/site-packages/exasol_integration_test_docker_environment/lib/base/base_task.py", line 239, in run
        task_generator = self.run_task()
      File "/home/vagrant/.cache/pypoetry/virtualenvs/exasol-script-languages-container-tool-fEttNriu-py3.8/lib/python3.8/site-packages/exasol_integration_test_docker_environment/lib/test_environment/database_setup/populate_data.py", line 42, in run_task
        raise Exception("Failed to populate the database with data.\nLog: %s" % cmd + "\n" + output.decode("utf-8"))
    Exception: Failed to populate the database with data.
    Log: cd /tests_data/enginedb_small; $EXAPLUS -c '172.18.0.2:8888' -x -u 'sys' -p 'exasol' -f import.sql -jdbcparam 'validateservercertificate=0'
    EXAplus 7.0.11 (c) EXASOL AG
    
    Tuesday, June 6, 2023 at 8:19:40 AM Coordinated Universal Time
    Connected to database DB1 as user sys.
    EXASolution 7.1.17 (c) EXASOL AG
    
    EXA: CREATE SCHEMA TEST;
    Error: [42500] schema TEST already exists (Session: 1767940639488868352)
    
    Disconnected.

```

**Comment by tkilias** [comment]
The problem is that we don't skip PopulateTestEngine, when reusing the DB.

**Comment by ckunki** [comment]
1. review round - some proposals
